name: CI

on: 
  pull_request:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: PHP Linting
      uses: michaelw90/php-lint@master
